title: Pag para probar GitHub Pages
author: Diego Parra
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Es muy importante aprender bien a utilizar estas cosas, 
  hubiera sido genial si en la carrera se mencionara esta herramienta,
  pero el tutorial esta genial

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
